# Makefile for example programs that demonstrate different features of
# the Adept library
#
# Note that this Makefile is hand-coded rather than being generated by
# automake
#
# The -DADEPT_RECORDING_PAUSABLE option enables the pause_recording
# and continue_recording functionality and is used by test_adept,
# although it will run correctly (but slightly more slowly) without
# this flag

# The configure script writes the following file, which contains
# variables controlling the compilation
include makefile_include

ADEPT_DIR = /mnt/home/mkuchera/external/Adept-2
LIBTOOL = $(ADEPT_DIR)/libtool
# Uncomment the following to check what happens if thread safety
# disabled
# ADEPT_FLAGS = -DADEPT_STACK_THREAD_UNSAFE

# The objects to create
OBJECTS = algorithm.o algorithm_noad.o test_checkpoint.o \
	test_adept.o test_adept_with_and_without_ad.o \
	test_radiances.o simulate_radiances.o test_thread_safe.o \
	test_no_lib.o test_misc.o test_arrays.o test_array_speed.o \
	test_radiances_array.o test_fixed_arrays.o
GSL_OBJECTS = test_gsl_interface.o state.o rosenbrock_banana_function.o

GSL_LIBS = -lgsl

COMPILE_FLAGS = $(CXXFLAGS) $(CPPFLAGS) $(ADEPT_FLAGS) -I$(ADEPT_DIR)/include

# Because we aren't going to install the test programs, and we want
# them to work even if Adept is not installed, it is easiest to use
# libtool to create statically-linked executables
top_builddir = $(ADEPT_DIR)
CXXLINK = $(LIBTOOL) --tag=CXX --mode=link $(CXX) $(CXXFLAGS) \
	-static -no-install -L$(ADEPT_DIR)/adept/.libs $(LDFLAGS) -ladept -o $@

# Dependency on the presence of the Adept static library
LIBADEPT = $(ADEPT_DIR)/adept/.libs/libadept.a

MYLIBS = $(LIBS)

PROGRAMS = test_adept BNN_adept

all:
	@echo "********************************************************"
	@echo "*** To compile test programs in test/ and benchmark/ ***"
	@echo "*** type \"make check\"                                ***"
	@echo "********************************************************"

# Compile all four programs
check: $(PROGRAMS)

# Test program 1
test_adept: algorithm.o test_adept.o $(LIBADEPT)
	$(CXXLINK) algorithm.o test_adept.o $(MYLIBS)
# Test program 2
BNN_adept: algorithm.o BNN_adept.o $(LIBADEPT)
	$(CXXLINK) algorithm.o BNN_adept.o $(MYLIBS)



# Test program 5
test_misc: test_misc.o algorithm.o $(LIBADEPT)
	$(CXXLINK) test_misc.o algorithm.o $(MYLIBS)

# Test program 6
test_checkpoint: test_checkpoint.o $(LIBADEPT)
	$(CXXLINK) test_checkpoint.o $(MYLIBS)

# Test program 7
test_thread_safe: test_thread_safe.o $(LIBADEPT)
	$(CXXLINK) test_thread_safe.o $(MYLIBS)

# Test program 8 (note that it is not linked against the Adept library)
test_no_lib: test_no_lib.o algorithm.o
	$(CXXLINK) test_no_lib.o algorithm.o

# Test program 9
test_arrays: test_arrays.o $(LIBADEPT)
	$(CXXLINK) test_arrays.o $(MYLIBS)

# Test program 10
test_array_speed: test_array_speed.o $(LIBADEPT)
	$(CXXLINK) test_array_speed.o $(MYLIBS)

# Test program 11
test_radiances_array: simulate_radiances.o test_radiances_array.o $(LIBADEPT)
	$(CXXLINK) simulate_radiances.o test_radiances_array.o $(MYLIBS)

# Test program 12
test_fixed_arrays: test_fixed_arrays.o $(LIBADEPT)
	$(CXXLINK) test_fixed_arrays.o $(MYLIBS)


# The no-automatic-differentiation version of the algorithm: uses the
# -DADEPT_NO_AUTOMATIC_DIFFERENTIATION to produce a version of the
# algorithm that takes double rather than adouble arguments
algorithm_noad.o: algorithm.cpp *.h ${ADEPT_DIR}/include/adept.h
	$(CXX) $(COMPILE_FLAGS) $(INCLUDES) -c algorithm.cpp -DADEPT_NO_AUTOMATIC_DIFFERENTIATION -o $@

# All other object files created by compiling the corresponding source
# file without this flag
%.o: %.cpp *.h ${ADEPT_DIR}/include/adept.h
	$(CXX) $(COMPILE_FLAGS) $(INCLUDES) -c $<

# Remove all object files and executables
clean:
	rm -f $(OBJECTS) $(GSL_OBJECTS) $(PROGRAMS)

mostlyclean: clean

# Null targets to satisfy autotools
EMPTY_AUTOMAKE_TARGETS = distdir install install-data install-exec uninstall \
	install-dvi install-html install-info install-ps install-pdf \
	installdirs installcheck distclean maintainer-clean \
	dvi pdf ps info html tags ctags
.PHONY: $(EMPTY_AUTOMAKE_TARGETS)
$(EMPTY_AUTOMAKE_TARGETS):
